name: Free VPS with Cloudflare Tunnel

on:
  workflow_dispatch:  # กดรันเองได้
  schedule:
    - cron: "0 */6 * * *"  # รันใหม่ทุก 6 ชั่วโมง

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cloudflare Tunnel
        run: |
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin

      - name: Start VPS with Cloudflare Tunnel
        run: |
          nohup cloudflared tunnel --url ssh://localhost:22 --no-autoupdate &  
          sudo apt update && sudo apt install -y openssh-server
          sudo service ssh start
          echo "root:password" | sudo chpasswd
          echo "🔥 VPS Running! Connect using: 'ssh root@your-domain.com -p 22'"
