name: Free VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      
      - name: Start VPS
        run: |
          nohup ngrok tcp 22 &  # เปิดพอร์ต SSH
          sudo apt update && sudo apt install -y openssh-server
          sudo service ssh start
          echo "root:password" | sudo chpasswd
          echo "🔥 VPS Running! Use 'ssh root@<ngrok-address>'"
